setup:
  debug: false

# twig setup
twig:
  debug: false
  cache: false

# basic site js/css includes
javascript:
  - common:*
  - site.js
  - https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js
css:
  - common:*
  - site.css
  - https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
